import 'package:skitmaker/models/skit_model.dart';
import 'package:skitmaker/models/user_model.dart';

// User currentUser = User(
//   1,
//   'wisdom@gmail.com',
//   '12345',
//   'Wisdom Ugo',
//   'Wisdom',
//   '08032322234',
//   'Male',
//   "images/profiles/profile_img.jpg",
// );
// User user1 = User(
//   '2',
//   'vincent@gmail.com',
//   '12345',
//   'Prof Vincent',
//   'ProfVin',
//   '08032322234',
//   'Male',
//   "images/profiles/profile1.png",
// );
// User user2 = User(
//   '3',
//   'tochi@gmail.com',
//   '12345',
//   'Tochi John',
//   'Tochi The One',
//   '08032322234',
//   'Female',
//   "images/profiles/profile2.png",
// );
// User user3 = User(
//   '4',
//   'jerry@gmail.com',
//   '12345',
//   'Jerry Deo',
//   'Jerry',
//   '08032322234',
//   'Male',
//   "images/profiles/profile3.png",
// );
// User user4 = User(
//   '5',
//   'phil@gmail.com',
//   '12345',
//   'Philemon Amos',
//   'Philemona',
//   '08032322234',
//   'Female',
//   "images/profiles/profile4.jpeg",
// );

var maker = ({
  1,
  'Wisdom',
  'wisdom@gmail.com',
  '12345',
  'Wisdom Ugo',
  '08032322234',
  'Male',
  "images/profiles/profile_img.jpg",
});

final List skits = [];
Skit sampleSkit = Skit(
  skitType: "short",
  uid: 'sdsds',
  username: 'username',
  id: 'skitid',
  likes: [],
  views: 3,
  commentCount: 4,
  shareCount: 6,
  category: 'category',
  skitTitle: 'skitTitle',
  description: 'description',
  tags: 'tags',
  skitUrl: 'skitUrl',
  thumbnail: 'thumbnail',
  profileImage: 'profileImage',
  dateCreated: DateTime.now(),
);

// final List<Skits> skits = [
//   Skits(
//       0,
//       "Wisdom Ugo",
//       "Splinter cell Blacklist - Safe House",
//       "Action",
//       "This is is the description of this skit This is is the description of this skit",
//       "images/thumbnails/thumbnail1.png",
//       "1.1M",
//       "7 months",
//       "2k",
//       "102",
//       ['tag1', 'tag2', 'tag3'],
//       "images/videos/video.mp4"),
//   Skits(
//       1,
//       "Wisdom Ugo",
//       "She rejected Me For Being Visually Challenged",
//       "Animation",
//       "This is is the description of this skit This is is the description of this skit This is is the description of this skit This is is the description of this skit",
//       "images/thumbnails/thumbnail2.png",
//       "124K",
//       "2 months",
//       "12k",
//       "142",
//       ['tag1', 'tag2', 'tag3'],
//       "images/videos/video1.mp4"),
//   Skits(
//       2,
//       "Wisdom Ugo",
//       "Manchester City VS Chelsea",
//       "Sports",
//       "This is is the description of this skit This is is the description of this skit",
//       "images/thumbnails/thumbnail3.png",
//       "12K",
//       "2days",
//       "22k",
//       "132",
//       ['tag1', 'tag2', 'tag3'],
//       "images/videos/video2.mp4"),
//   Skits(
//       3,
//       "Wisdom Ugo",
//       "Baby Buck Lost in Highlands of Nairobi Without Mother",
//       "Documentary",
//       "This is is the description of this skit This is is the description of this skit",
//       "images/thumbnails/thumbnail4.png",
//       "1.2M",
//       "2 years",
//       "8k",
//       "23",
//       ['tag1', 'tag2', 'tag3'],
//       "images/videos/video3.mp4"),
//   Skits(
//       4,
//       "Wisdom Ugo",
//       "Russia / Ukrain War - The Battle of Pride",
//       "War",
//       "This is is the description of this skit This is is the description of this skit This is is the description of this skit This is is the description of this skit",
//       "images/thumbnails/thumbnail5.png",
//       "124k",
//       "2 months",
//       "24k",
//       "402",
//       ['tag1', 'tag2', 'tag3'],
//       "images/videos/video4.mp4"),
//   Skits(
//       5,
//       "Wisdom Ugo",
//       "The Untold stroy of the Deep Forest of Angola",
//       "Documentary",
//       "This is is the description of this skit This is is the description of this skit",
//       "images/thumbnails/thumbnail6.png",
//       "124",
//       "2 day",
//       "1k",
//       "13",
//       ['tag1', 'tag2', 'tag3'],
//       "images/videos/video5.mp4"),
//   Skits(
//       6,
//       "Wisdom Ugo",
//       "The Rise of the Setting Sun",
//       "Action",
//       "This is is the description of this skit This is is the description of this skit This is is the description of this skit This is is the description of this skit",
//       "images/thumbnails/thumbnail7.png",
//       "1k",
//       "5 days",
//       "2k",
//       "45",
//       ['tag1', 'tag2', 'tag3'],
//       "images/videos/video3.mp4"),
//   Skits(
//       7,
//       "Wisdom Ugo",
//       "The Cheerleaders Love Tale",
//       "Romance",
//       "This is is the description of this skit This is is the description of this skit",
//       "images/thumbnails/thumbnail8.png",
//       "111k",
//       "1 year",
//       "2k",
//       "102",
//       ['tag1', 'tag2', 'tag3'],
//       "images/videos/video.mp4")
// ];

// Skits sampleSkit = Skits(
//   0,
//   "Wisdom Ugo",
//   "Splinter cell Blacklist - Safe House",
//   "Action",
//   "This is is the description of this skit This is is the description of this skit",
//   "images/thumbnails/thumbnail1.png",
//   "1.1M",
//   "7 months",
//   "2k",
//   "102",
//   ['tag1', 'tag2', 'tag3'],
//   "images/videos/video.mp4",
// );
